name = "rss-doc"
main = "worker.js"
compatibility_date = "2023-12-01"

# 资源配置
[site]
bucket = ".next"

# 资源绑定
[[d1_databases]]
binding = "DB"
database_name = "figma_app_db"
database_id = ""

# 绑定 Assets 命名空间
[[kv_namespaces]]
binding = "ASSETS"
id = ""

# 环境配置
[env.production]
name = "figma-app-prod" 